METRONOME = 13
BANK_UP = -100
BANK_DOWN = -100
EXIT = 24
VOL_UP = 4444444
VOL_DOWN = 555555
CLEAR_LOOP = 19
RECORD = 25  # 18

BPM_CONTROL = 6
BPM_UP = 20
BPM_DOWN = 21
MBUNG_VOL_CONTROL = 0
COL_VOL_CONTROL = 1
PITCH_CONTROL = 10
PITCH_UP = 22
PITCH_DOWN = 23
PAD_START = 52
LOOP_SELECTOR = 15
BANK_SELECTOR = 11
PAGE_SELECTOR = 12
SAVE_LOOP = 16
MODE_SHIFT = 26

#Mode nums - hold down MODE_SHIFT and press pads 1-16
AUDIO_RECORD_MODE_NUM = 2 # pad 2
VELOCITY_SENSITIVITY = 3 # 25 pad 3

PADS = range(PAD_START,PAD_START+16)
SHIFT_BUTTONS = [BANK_SELECTOR,METRONOME,LOOP_SELECTOR, MODE_SHIFT,PAGE_SELECTOR]
SWITCH_BUTTONS = [PITCH_UP,PITCH_DOWN,BPM_UP,BPM_DOWN,RECORD,EXIT,VELOCITY_SENSITIVITY,CLEAR_LOOP]




